### ISSUE TITLE
Failed to connect to Rule34.xxx

### ISSUE THREAD

**Issue by VeryVeryCoolName** [Dax-Eleven/Rule34.xxx-Downloader#1]
I get the "You are offline, please check your internet connection" error every time I open the .exe

I can manually connect to rule34 when I open it on my browser and my internet connetion is working

![image_2023-03-04_105920719](https://user-images.githubusercontent.com/78220549/222886828-9f1fb3d0-74db-4796-b75d-c4a358448003.png)

**Comment by VeryVeryCoolName** [comment]
for some reason running the app with admin rights fixed this (I have no idea why)

**Comment by Dax-Eleven** [comment]
Hmm, that's strange
Are you using any vpn or something similar with admin rights?
Or maybe some antivirus blocked access to the https://rule34.xxx/ request?

**Comment by DaxEleven** [comment]
If you encounter this bug, please create an issue here
https://github.com/DaxEleven/Rule34.xxx-Downloader
